version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "securecabbage-auth-poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1j843uxe5ni2q"
s3_prefix = "securecabbage-auth-poc"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
